# Generated by Django 3.2.23 on 2023-11-07 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatementsModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('statement', models.CharField(max_length=500)),
                ('label', models.CharField(max_length=50)),
                ('probscore', models.FloatField()),
                ('logisticregression', models.CharField(max_length=50)),
                ('naivebayes', models.CharField(max_length=50)),
                ('randomforrest', models.CharField(max_length=50)),
                ('svm', models.CharField(max_length=50)),
                ('deepneural', models.CharField(max_length=50)),
                ('lgbinary', models.CharField(max_length=50)),
                ('naivebinary', models.CharField(max_length=50)),
                ('rfbinary', models.CharField(max_length=50)),
                ('svmbinary', models.CharField(max_length=50)),
                ('deepneuralbinary', models.CharField(max_length=50)),
                ('cdate', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'statementresults',
            },
        ),
        migrations.CreateModel(
            name='UserRegisterModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'registrations',
            },
        ),
    ]
